// Auto-generated from the original XACT audio project's raw .wav sources.
using System.Collections.Generic;

namespace Microsoft.Xna.Framework.Audio
{
    public static class AudioManifest
    {
        public static readonly Dictionary<string, string> CuePaths = new Dictionary<string, string>
        {
            { "accountant_death", "Audio/Death Noises/accountant_death" },
            { "act1", "Audio/SFX/act1" },
            { "alright", "Audio/Scene 1/SFX/alright" },
            { "announce", "Audio/Scene 1/Voice/announce" },
            { "argh", "Audio/SFX/argh" },
            { "bang", "Audio/SFX/bang" },
            { "beep", "Audio/Scene 1/SFX/beep" },
            { "ben_seib_death", "Audio/Death Noises/ben_seib_death" },
            { "boss_music", "Audio/Music/boss_music" },
            { "brush_teeth", "Audio/Scene 1/SFX/brush_teeth" },
            { "butabi_death", "Audio/Death Noises/butabi_death" },
            { "charging_face", "Audio/SFX/charging_face" },
            { "clock_hit", "Audio/Scene 1/SFX/clock_hit" },
            { "coral_death", "Audio/Death Noises/coral_death" },
            { "credits_song", "Audio/Music/credits_song" },
            { "cs1", "Audio/Scene 1/cs1" },
            { "cs2", "Audio/Scene 2/cs2" },
            { "cs3", "Audio/Scene 3/cs3" },
            { "cutscene2", "Audio/Scene 2/cutscene2" },
            { "cutscene2_a", "Audio/Scene 2/cutscene2_a" },
            { "cutscene2_b", "Audio/Scene 2/cutscene2_b" },
            { "cutscene2_c", "Audio/Scene 2/cutscene2_c" },
            { "cutscene2_d", "Audio/Scene 2/cutscene2_d" },
            { "cutscene2_e", "Audio/Scene 2/cutscene2_e" },
            { "cutscene2_f", "Audio/Scene 2/cutscene2_f" },
            { "cutscene2_g", "Audio/Scene 2/cutscene2_g" },
            { "cutscene2_h", "Audio/Scene 2/cutscene2_h" },
            { "cutscene2_i", "Audio/Scene 2/cutscene2_i" },
            { "cutscene2_j", "Audio/Scene 2/cutscene2_j" },
            { "cutscene2_j1", "Audio/Scene 2/cutscene2_j1" },
            { "cutscene2_j2", "Audio/Scene 2/cutscene2_j2" },
            { "cutscene2_k", "Audio/Scene 2/cutscene2_k" },
            { "dash", "Audio/SFX/dash" },
            { "definition", "Audio/Scene 1/SFX/definition" },
            { "dj_charge", "Audio/SFX/dj_charge" },
            { "do", "Audio/SFX/do" },
            { "door_hit", "Audio/Scene 1/SFX/door_hit" },
            { "fer", "Audio/SFX/fer" },
            { "fernando_teleport", "Audio/SFX/fernando_teleport" },
            { "fitty_cent_death", "Audio/Death Noises/fitty_cent_death" },
            { "forza", "Audio/SFX/forza" },
            { "get_out", "Audio/SFX/get_out" },
            { "go_down", "Audio/Scene 1/Voice/go_down" },
            { "go_noise", "Audio/SFX/go_noise" },
            { "ground_smash", "Audio/SFX/ground_smash" },
            { "growl", "Audio/Scene 1/SFX/growl" },
            { "guido_death", "Audio/Death Noises/guido_death" },
            { "guido_throw", "Audio/SFX/guido_throw" },
            { "help_lad", "Audio/Scene 1/SFX/help_lad" },
            { "hiya", "Audio/SFX/hiya" },
            { "introduction", "Audio/Scene 1/SFX/introduction" },
            { "land_noise", "Audio/SFX/land_noise" },
            { "laundry_get", "Audio/Scene 1/SFX/laundry_get" },
            { "main_club_music", "Audio/Music/main_club_music" },
            { "menu_beep", "Audio/SFX/menu_beep" },
            { "menu_music", "Audio/SFX/menu_music" },
            { "missed", "Audio/SFX/missed" },
            { "nan", "Audio/SFX/nan" },
            { "nicole_death", "Audio/Death Noises/nicole_death" },
            { "organic", "Audio/Scene 1/Voice/organic" },
            { "pah", "Audio/SFX/pah" },
            { "pew", "Audio/SFX/pew" },
            { "probably_duck", "Audio/Scene 1/SFX/probably_duck" },
            { "psh", "Audio/SFX/psh" },
            { "silvio_death", "Audio/Death Noises/silvio_death" },
            { "stage_clear", "Audio/SFX/stage_clear" },
            { "stelven_get_in", "Audio/Scene 1/Voice/stelven_get_in" },
            { "suicide_warning", "Audio/SFX/suicide_warning" },
            { "ten_years", "Audio/Scene 1/Voice/ten_years" },
            { "throw_noise", "Audio/SFX/throw_noise" },
            { "thump", "Audio/SFX/thump" },
            { "traffic_noise_a", "Audio/Scene 1/SFX/traffic_noise_a" },
            { "traffic_noise_b", "Audio/Scene 1/SFX/traffic_noise_b" },
            { "traffic_noise_c", "Audio/Scene 1/SFX/traffic_noise_c" },
            { "traffic_noise_d", "Audio/Scene 1/SFX/traffic_noise_d" },
            { "turbo_charge", "Audio/SFX/turbo_charge" },
            { "vip_music", "Audio/Music/vip_music" },
            { "walking_noise", "Audio/Scene 1/SFX/walking_noise" },
            { "what_is", "Audio/Scene 1/Voice/what_is" },
        };
    }
}